# Generated by Django 5.2.9 on 2025-12-27 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_producto", models.CharField(max_length=255)),
                (
                    "valor_unitario",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("stock", models.PositiveIntegerField(default=0)),
                ("bodega_ubicacion", models.CharField(max_length=255)),
                (
                    "imagen1",
                    models.ImageField(blank=True, null=True, upload_to="productos/"),
                ),
                (
                    "imagen2",
                    models.ImageField(blank=True, null=True, upload_to="productos/"),
                ),
                (
                    "imagen3",
                    models.ImageField(blank=True, null=True, upload_to="productos/"),
                ),
                (
                    "imagen4",
                    models.ImageField(blank=True, null=True, upload_to="productos/"),
                ),
                (
                    "imagen5",
                    models.ImageField(blank=True, null=True, upload_to="productos/"),
                ),
                (
                    "imagen6",
                    models.ImageField(blank=True, null=True, upload_to="productos/"),
                ),
                (
                    "imagen7",
                    models.ImageField(blank=True, null=True, upload_to="productos/"),
                ),
                (
                    "imagen8",
                    models.ImageField(blank=True, null=True, upload_to="productos/"),
                ),
                (
                    "imagen9",
                    models.ImageField(blank=True, null=True, upload_to="productos/"),
                ),
                (
                    "imagen10",
                    models.ImageField(blank=True, null=True, upload_to="productos/"),
                ),
                (
                    "imagen11",
                    models.ImageField(blank=True, null=True, upload_to="productos/"),
                ),
                (
                    "imagen12",
                    models.ImageField(blank=True, null=True, upload_to="productos/"),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.categoria",
                    ),
                ),
            ],
        ),
    ]
